# Generated by Django 4.2.6 on 2024-02-05 18:30

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(default="", max_length=100, verbose_name="City"),
        ),
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="last name"),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(default="", max_length=20, verbose_name="Postal/Zip Code"),
        ),
        migrations.AddField(
            model_name="user",
            name="province_state",
            field=models.CharField(default="", max_length=2, verbose_name="Province/State"),
        ),
        migrations.AddField(
            model_name="user",
            name="street_address",
            field=models.CharField(default="", max_length=255, verbose_name="Street Address"),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(
                error_messages={"unique": "A user with that username already exists."},
                help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                max_length=150,
                unique=True,
                validators=[django.contrib.auth.validators.UnicodeUsernameValidator()],
                verbose_name="username",
            ),
        ),
    ]
